repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: 'https://gitlab.com/pycqa/flake8'
    rev: 3.8.4
    hooks:
      - id: flake8
  - repo: 'https://github.com/pre-commit/mirrors-isort'
    rev: v5.7.0
    hooks:
      - id: isort
  - repo: 'https://github.com/mgedmin/check-manifest'
    rev: '0.46'
    hooks:
      - id: check-manifest
  - repo: 'https://github.com/myint/autoflake'
    rev: v1.4
    hooks:
      - id: autoflake
        args:
          - '--remove-all-unused-imports'
          - '-i'
        language_version: python3.9
  - repo: 'https://github.com/pre-commit/mirrors-autopep8'
    rev: v1.5.7
    hooks:
      - id: autopep8
        language_version: python3.9
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/ikamensh/flynt/
    rev: '0.76'
    hooks:
      - id: flynt
        language_version: python3.9
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py3-plus --py36-plus --keep-runtime-typing
        language_version: python3.9
